//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class defectitem
    {
        public int defectItemID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Reason { get; set; }
        public string HandleMethod { get; set; }
        public Nullable<double> RefundAmount { get; set; }
        public string SupplierReply { get; set; }
        public string Handle { get; set; }
        public Nullable<System.DateTime> dateofreturn { get; set; }
    }
}
