//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryorder
    {
        public int DeliveryOrderID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DWorkerID { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.TimeSpan> timeofDelivery { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string D_Status { get; set; }
        public int DeliveryProductID_1 { get; set; }
        public Nullable<int> DeliveryProductID_2 { get; set; }
        public Nullable<int> DeliveryProductID_3 { get; set; }
        public Nullable<int> DeliveryProductID_4 { get; set; }
        public Nullable<int> DeliveryProductID_5 { get; set; }
        public Nullable<int> DeliveryProductID_6 { get; set; }
        public Nullable<int> DeliveryProductID_7 { get; set; }
        public Nullable<int> DeliveryProductID_8 { get; set; }
        public Nullable<int> DeliveryProductID_9 { get; set; }
        public Nullable<int> DeliveryProductID_10 { get; set; }
        public int DeliveryProductID_1qty { get; set; }
        public int DeliveryProductID_2qty { get; set; }
        public int DeliveryProductID_3qty { get; set; }
        public int DeliveryProductID_4qty { get; set; }
        public int DeliveryProductID_5qty { get; set; }
        public int DeliveryProductID_6qty { get; set; }
        public int DeliveryProductID_7qty { get; set; }
        public int DeliveryProductID_8qty { get; set; }
        public int DeliveryProductID_9qty { get; set; }
        public int DeliveryProductID_10qty { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
        public virtual product product2 { get; set; }
        public virtual product product3 { get; set; }
        public virtual product product4 { get; set; }
        public virtual product product5 { get; set; }
        public virtual product product6 { get; set; }
        public virtual product product7 { get; set; }
        public virtual product product8 { get; set; }
        public virtual session session { get; set; }
    }
}
