//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class installationorder
    {
        public int InstallationOrderID { get; set; }
        public Nullable<int> SaleOrderID { get; set; }
        public Nullable<int> I_Worker { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string I_status { get; set; }
        public System.TimeSpan InstallationTime { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public int InstallProduct1 { get; set; }
        public int InstallProduct2 { get; set; }
        public int InstallProduct3 { get; set; }
        public int InstallProduct4 { get; set; }
        public int InstallProduct5 { get; set; }
        public int InstallProduct6 { get; set; }
        public int InstallProduct7 { get; set; }
        public int InstallProduct8 { get; set; }
        public int InstallProduct9 { get; set; }
        public int InstallProduct10 { get; set; }
        public int InstallProduct1_qty { get; set; }
        public int InstallProduct2_qty { get; set; }
        public int InstallProduct3_qty { get; set; }
        public int InstallProduct4_qty { get; set; }
        public int InstallProduct5_qty { get; set; }
        public int InstallProduct6_qty { get; set; }
        public int InstallProduct7_qty { get; set; }
        public int InstallProduct8_qty { get; set; }
        public int InstallProduct9_qty { get; set; }
        public int InstallProduct10_qty { get; set; }
        public int InstallationStaffID { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
        public virtual product product2 { get; set; }
        public virtual product product3 { get; set; }
        public virtual product product4 { get; set; }
        public virtual product product5 { get; set; }
        public virtual product product6 { get; set; }
        public virtual product product7 { get; set; }
        public virtual product product8 { get; set; }
        public virtual product product9 { get; set; }
    }
}
