//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class betterlimitedEntities_Test1 : DbContext
    {
        public betterlimitedEntities_Test1()
            : base("name=betterlimitedEntities_Test1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<defectitem> defectitems { get; set; }
        public virtual DbSet<deliveryorder> deliveryorders { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<installationorder> installationorders { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<purchaseitem> purchaseitems { get; set; }
        public virtual DbSet<purchasingorder> purchasingorders { get; set; }
        public virtual DbSet<reorder> reorders { get; set; }
        public virtual DbSet<saleorder> saleorders { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<shoprecovery> shoprecoveries { get; set; }
        public virtual DbSet<soldproduct> soldproducts { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<type> types { get; set; }
    }
}
