//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.deliveryorders = new HashSet<deliveryorder>();
            this.deliveryorders1 = new HashSet<deliveryorder>();
            this.deliveryorders2 = new HashSet<deliveryorder>();
            this.deliveryorders3 = new HashSet<deliveryorder>();
            this.deliveryorders4 = new HashSet<deliveryorder>();
            this.deliveryorders5 = new HashSet<deliveryorder>();
            this.deliveryorders6 = new HashSet<deliveryorder>();
            this.deliveryorders7 = new HashSet<deliveryorder>();
            this.deliveryorders8 = new HashSet<deliveryorder>();
            this.installationorders = new HashSet<installationorder>();
            this.installationorders1 = new HashSet<installationorder>();
            this.installationorders2 = new HashSet<installationorder>();
            this.installationorders3 = new HashSet<installationorder>();
            this.installationorders4 = new HashSet<installationorder>();
            this.installationorders5 = new HashSet<installationorder>();
            this.installationorders6 = new HashSet<installationorder>();
            this.installationorders7 = new HashSet<installationorder>();
            this.installationorders8 = new HashSet<installationorder>();
            this.installationorders9 = new HashSet<installationorder>();
            this.reorders = new HashSet<reorder>();
            this.reorders1 = new HashSet<reorder>();
            this.reorders2 = new HashSet<reorder>();
            this.reorders3 = new HashSet<reorder>();
            this.reorders4 = new HashSet<reorder>();
            this.reorders5 = new HashSet<reorder>();
            this.reorders6 = new HashSet<reorder>();
            this.reorders7 = new HashSet<reorder>();
            this.reorders8 = new HashSet<reorder>();
            this.reorders9 = new HashSet<reorder>();
        }
    
        public int ProductID { get; set; }
        public int Reorder { get; set; }
        public Nullable<int> RequireInstall { get; set; }
        public string SerialNum { get; set; }
        public string ProductName { get; set; }
        public int Available { get; set; }
        public int TypeID { get; set; }
        public int Price { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> StockLevel { get; set; }
        public int Low_Standard { get; set; }
        public int KBStore { get; set; }
        public Nullable<int> KBdisplay { get; set; }
        public int TWStore { get; set; }
        public Nullable<int> TWdisplay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deliveryorder> deliveryorders8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installationorder> installationorders9 { get; set; }
        public virtual purchaseitem purchaseitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reorder> reorders9 { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual type type { get; set; }
    }
}
