//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseitem
    {
        public int PurchaseOrderID { get; set; }
        public int ProductID { get; set; }
        public int Quanity { get; set; }
        public double Price { get; set; }
        public string Status { get; set; }
    
        public virtual product product { get; set; }
        public virtual purchasingorder purchasingorder { get; set; }
    }
}
