//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorder
    {
        public int ReorderID { get; set; }
        public System.DateTime ReorderCreatedDate { get; set; }
        public string Approve { get; set; }
        public int Product1 { get; set; }
        public Nullable<int> Product2 { get; set; }
        public Nullable<int> Product3 { get; set; }
        public Nullable<int> Product4 { get; set; }
        public Nullable<int> Product5 { get; set; }
        public Nullable<int> Product6 { get; set; }
        public Nullable<int> Product7 { get; set; }
        public Nullable<int> Product8 { get; set; }
        public Nullable<int> Product9 { get; set; }
        public Nullable<int> Product10 { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product11 { get; set; }
        public virtual product product12 { get; set; }
        public virtual product product13 { get; set; }
        public virtual product product14 { get; set; }
        public virtual product product15 { get; set; }
        public virtual product product16 { get; set; }
        public virtual product product17 { get; set; }
        public virtual product product18 { get; set; }
        public virtual product product19 { get; set; }
    }
}
