//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleorder
    {
        public int orderID { get; set; }
        public System.DateTime Date_Of_Purchase { get; set; }
        public string orderType { get; set; }
        public Nullable<int> DeliveryOrderID { get; set; }
        public Nullable<int> InstallationOrderID { get; set; }
        public Nullable<int> storeID { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public double TotalCharge { get; set; }
        public Nullable<double> Addition_Charge { get; set; }
        public Nullable<double> DepositCharge { get; set; }
        public Nullable<double> PayAmount { get; set; }
        public string PayMethod { get; set; }
        public string Active { get; set; }
        public Nullable<int> Product1_ID { get; set; }
        public Nullable<int> Product1_Qty { get; set; }
        public Nullable<int> Product2_ID { get; set; }
        public Nullable<int> Product2_Qty { get; set; }
        public Nullable<int> Product3_ID { get; set; }
        public Nullable<int> Product3_Qty { get; set; }
        public Nullable<int> Product4_ID { get; set; }
        public Nullable<int> Product4_Qty { get; set; }
        public Nullable<int> Product5_ID { get; set; }
        public Nullable<int> Product5_Qty { get; set; }
        public Nullable<int> Product6_ID { get; set; }
        public Nullable<int> Product6_Qty { get; set; }
        public Nullable<int> Product7_ID { get; set; }
        public Nullable<int> Product7_Qty { get; set; }
        public Nullable<int> Product8_ID { get; set; }
        public Nullable<int> Product8_Qty { get; set; }
        public Nullable<int> Product9_ID { get; set; }
        public Nullable<int> Product9_Qty { get; set; }
        public Nullable<int> Product10_ID { get; set; }
        public Nullable<int> Product10_Qty { get; set; }
        public Nullable<int> Product1_display { get; set; }
        public Nullable<int> Product2_display { get; set; }
        public Nullable<int> Product3_display { get; set; }
        public Nullable<int> Product4_display { get; set; }
        public Nullable<int> Product5_display { get; set; }
        public Nullable<int> Product6_display { get; set; }
        public Nullable<int> Product7_display { get; set; }
        public Nullable<int> Product8_display { get; set; }
        public Nullable<int> Product9_display { get; set; }
        public Nullable<int> Product10_display { get; set; }
    }
}
