//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public System.DateTime dateofservice { get; set; }
        public int SessionID { get; set; }
        public int D_staffID { get; set; }
        public int D_staff2ID { get; set; }
        public int I_staffID { get; set; }
        public int I_staffID2 { get; set; }
    
        public virtual session session { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
        public virtual staff staff2 { get; set; }
        public virtual staff staff3 { get; set; }
    }
}
