//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoprecovery
    {
        public int recoveryid { get; set; }
        public int ProductID { get; set; }
        public int Quanity { get; set; }
        public string status { get; set; }
        public System.DateTime dateofcreate { get; set; }
        public int StoreID { get; set; }
        public Nullable<System.DateTime> dateofrecover { get; set; }
        public string Reason { get; set; }
    }
}
