//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterLimited
{
    using System;
    using System.Collections.Generic;
    
    public partial class soldproduct
    {
        public int soldproductid { get; set; }
        public int SaleorderID { get; set; }
        public int productID { get; set; }
        public double ProductPrePrice { get; set; }
        public int Quantity { get; set; }
        public int Displayed { get; set; }
        public double TotalAmount { get; set; }
        public string Able { get; set; }
    }
}
